# Generated by Django 4.2.4 on 2023-09-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
